
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode8

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

before_install:
#  - sudo update-java-alternatives -s java-8-oracle
#  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
#  - java -version
#  - brew update


- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://swift.org/builds/development/ubuntu1404/swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a/swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then tar xzvf swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-ubuntu14.04.tar.gz    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=swift-DEVELOPMENT-SNAPSHOT-2016-07-27-a-ubuntu14.04/usr/bin:$PATH    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install clang libicu-dev libkqueue-dev libtool libcurl4-openssl-dev libbsd-dev libblocksruntime-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone -b experimental/foundation https://github.com/apple/swift-corelibs-libdispatch.git && cd swift-corelibs-libdispatch && git submodule init && git submodule update && sh autogen.sh && ./configure --with-swift-toolchain=${PWD}/../swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-ubuntu14.04/usr --prefix=${PWD}/../swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-ubuntu14.04/usr && make && make install && cd ..   ; fi
  - git submodule init && git submodule update


  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall git ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git openssl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a/swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-osx.pkg    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-07-25-a-osx.pkg -target /    ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"    ; fi 

  - sudo rm -rf /var/lib/cassandra/*
  - wget http://www.us.apache.org/dist/cassandra/3.7/apache-cassandra-3.7-bin.tar.gz && tar -xvzf apache-cassandra-3.7-bin.tar.gz
  - sudo sh ./apache-cassandra-3.7/bin/cassandra -R
  - sleep 20


script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift build -Xcc -fblocks -Xcc -I/usr/opt/openssl/include -Xlinker -rpath -Xlinker .build/debug ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift build -Xcc -I/usr/local/opt/openssl/include -Xlinker -L/usr/local/opt/openssl/lib ; fi
  - swift test
